client_config_backend: file
client_config:
    client_id: 491816159564-290fdflu50e580qhumlnhqrmhmcl35ni.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive